# Generated by Django 5.2.5 on 2025-08-20 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TeamModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fullName",
                    models.CharField(max_length=100, verbose_name="Full Name"),
                ),
                ("position", models.CharField(max_length=100, verbose_name="Position")),
                ("bio", models.TextField(blank=True, null=True, verbose_name="Bio")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="team_images/",
                        verbose_name="Profile Image",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "join_date",
                    models.DateField(auto_now_add=True, verbose_name="Join Date"),
                ),
            ],
            options={
                "verbose_name": "Team Member",
                "verbose_name_plural": "Team Members",
                "ordering": ["fullName"],
            },
        ),
        migrations.CreateModel(
            name="SocialModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("linkedin", "LinkedIn"),
                            ("twitter", "Twitter"),
                            ("github", "GitHub"),
                            ("instagram", "Instagram"),
                            ("facebook", "Facebook"),
                            ("portfolio", "Portfolio"),
                            ("email", "Email"),
                        ],
                        max_length=20,
                        verbose_name="Platform",
                    ),
                ),
                ("url", models.URLField(verbose_name="URL")),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="Primary Social"),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="socials",
                        to="teams.teammodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Social Media",
                "verbose_name_plural": "Social Media Links",
                "unique_together": {("team", "platform")},
            },
        ),
    ]
