# Generated by Django 5.2.5 on 2025-08-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teammodel",
            options={
                "ordering": ["order", "id"],
                "verbose_name": "Team Member",
                "verbose_name_plural": "Team Members",
            },
        ),
        migrations.AddField(
            model_name="teammodel",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Display Order"),
        ),
    ]
