# Generated by Django 5.2.5 on 2025-08-15 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WorkShop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "workshop_name",
                    models.CharField(max_length=255, verbose_name="Workshop Name"),
                ),
                ("workshop_date", models.DateField(verbose_name="Workshop Date")),
                (
                    "workshop_location",
                    models.CharField(max_length=255, verbose_name="Workshop Location"),
                ),
                (
                    "workshop_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Workshop Description"
                    ),
                ),
            ],
            options={
                "verbose_name": "Workshop",
                "verbose_name_plural": "Workshops",
                "ordering": ["workshop_date"],
            },
        ),
        migrations.CreateModel(
            name="WorkshopRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_name",
                    models.CharField(max_length=255, verbose_name="User Name"),
                ),
                (
                    "user_email",
                    models.EmailField(max_length=254, verbose_name="User Email"),
                ),
                (
                    "will_attend_physical",
                    models.BooleanField(
                        default=True, verbose_name="Will Attend Physically"
                    ),
                ),
                (
                    "django_experience",
                    models.CharField(
                        choices=[
                            ("Beginner", "Beginner"),
                            ("Intermediate", "Intermediate"),
                            ("Advanced", "Advanced"),
                        ],
                        default="Beginner",
                        max_length=20,
                        verbose_name="Django Experience Level",
                    ),
                ),
                (
                    "registration_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Registration Date"
                    ),
                ),
                (
                    "workshop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="core.workshop",
                        verbose_name="Workshop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workshop Registration",
                "verbose_name_plural": "Workshop Registrations",
                "ordering": ["registration_date"],
            },
        ),
    ]
