# Generated by Django 5.2.5 on 2025-08-16 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_workshop_workshop_image_header_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workshopregistration",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=13, null=True, verbose_name="Phone Number"
            ),
        ),
    ]
