# Generated by Django 5.2.5 on 2025-08-16 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_workshopregistration_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workshop",
            name="workshop_image_header",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="header/workshop_images/",
                verbose_name="Workshop Image Header",
            ),
        ),
    ]
