# Generated by Django 5.2.5 on 2025-08-16 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_workshop_workshop_image_header"),
    ]

    operations = [
        migrations.AddField(
            model_name="workshop",
            name="is_ended",
            field=models.BooleanField(default=False, verbose_name="Is Ended"),
        ),
    ]
