# Generated by Django 5.2.5 on 2025-09-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_workshop_is_ended"),
    ]

    operations = [
        migrations.AddField(
            model_name="workshop",
            name="workshop_time",
            field=models.TimeField(blank=True, null=True, verbose_name="Workshop Time"),
        ),
    ]
