# Generated by Django 5.2.5 on 2025-10-18 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_workshop_workshop_time"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workshop",
            options={
                "ordering": ["-workshop_date", "-id"],
                "verbose_name": "Workshop",
                "verbose_name_plural": "Workshops",
            },
        ),
    ]
